# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='text',
            field=models.TextField(),
        ),
    ]
