# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20180409_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='text',
            new_name='list',
        ),
    ]
