# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20180409_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='list',
            new_name='text1',
        ),
    ]
